name: OneSlotServer
version: ${project.version}
main: com.freundtech.minecraft.oneslotserver.OneSlotServer
api-version: 1.13
authors: [freundTech]
commands:
  spectate:
    description: Go into spectator mode
    usage: /spectate [player]
    permission: oneslotserver.spectate
    permission-message: You don't have permission to do this
  unspectate:
    description: Leave spectator mode
    usage: /unspectate [player]
    permission: oneslotserver.spectate
    permission-message: You don't have permission to do this
permissions:
  oneslotserver.spectate:
    description: Allows a player to spectate
    default: op
  oneslotserver.seespectators:
    description: Allows a player to see spectators in the tab list
    default: op
