name: OneSlotServer
version: "1.0"
main: com.freundtech.minecraft.oneslotserver.OneSlotServer
api-version: "1.13"
authors: [freundTech]
commands:
  spectate:
    description: Go into spectator mode
    usage: /spectate [player]
    permission: oneslotserver.spectate
  unspectate:
    description: Leave spectator mode
    usage: /unspectate [player]
    permission: oneslotserver.spectate
  setplaytime:
    description: Set the allowed play time
    usage: /setplaytime [seconds]
    permission: oneslotserver.time.global
  setwaittime:
    description: Set the enforces wait time
    usage: /setwaittime [seconds]
    permission: oneslotserver.time.global
  settimeleft:
    description: Set the time left for the current player
    usage: /settimeleft [seconds]
    permission: oneslotserver.time.player
permissions:
  oneslotserver.spectate:
    description: Allows a player to spectate
    default: op
  oneslotserver.seespectators:
    description: Allows a player to see spectators in the tab list
    default: op
  oneslotserver.time.player:
    description: Allows players to set remaining and wait time for players
    default: op
  oneslotserver.time.global:
    description: Allows players to set play and wait time globally
    default: op
  oneslotserver.time:
    default: op
    children:
      - oneslotserver.settime.player
      - oneslotserver.settime.global
